/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SingleChoicePropertyPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/settings-tab.ts
var import_obsidian3 = require("obsidian");

// src/i18n.ts
var import_obsidian = require("obsidian");

// src/i18n/locales/en.ts
var en = {
  notices: {
    keptLatestValue: 'Detected multiple values in {property} for "{file}". Updated automatically and kept: {value}',
    enterPropertyName: "Enter a property name first.",
    alreadyWatched: "{property} is already watched.",
    convertedPropertyType: "Converted {property} property type to list."
  },
  settings: {
    watchedPropertiesName: "Single value property",
    watchedPropertiesDesc: "Select and add list-type properties.",
    showNoticeName: "Notify when modifying properties",
    showNoticeDesc: "Show a notification when the plugin automatically modifies a property.",
    addButton: "Add",
    warning: "Some watched properties are not list types in Obsidian property settings, so the plugin cannot take effect. Convert them before relying on automatic cleanup.",
    uniquePropertiesGroup: "Single value property list",
    uniquePropertiesDesc: "The following properties only keep a single value. This is useful for single-choice properties such as priority.",
    uniquePropertiesUpdateDesc: "Whenever a property changes, it is updated automatically and shows a notice.",
    removeTooltip: "Remove",
    convertPropertyTypeButton: "Convert property type",
    convertPropertyTypeTooltip: "Convert this property to a list type. This only affects the property type and will not modify existing notes.",
    configuredAsList: "This property is configured as a list type. When a new value is added, only the latest value is kept to ensure uniqueness.",
    notRegistered: "This property is not registered in Obsidian property settings.",
    notListType: "This property is currently {type}, not a list type, so the plugin cannot take effect."
  }
};
var en_default = en;

// src/i18n/locales/zh.ts
var zh = {
  notices: {
    keptLatestValue: "\u68C0\u6D4B\u5230\u201C{file}\u201D\u7684 {property} \u5B58\u5728\u591A\u503C\uFF0C\u5DF2\u81EA\u52A8\u66F4\u65B0\uFF0C\u4FDD\u7559\u503C\uFF1A{value}",
    enterPropertyName: "\u8BF7\u5148\u8F93\u5165\u5C5E\u6027\u540D\u3002",
    alreadyWatched: "{property} \u5DF2\u7ECF\u5728\u76D1\u542C\u5217\u8868\u4E2D\u3002",
    convertedPropertyType: "\u5DF2\u5C06 {property} \u7684\u5C5E\u6027\u7C7B\u578B\u8F6C\u6362\u4E3A\u5217\u8868\u3002"
  },
  settings: {
    watchedPropertiesName: "\u5355\u4E00\u503C\u5C5E\u6027",
    watchedPropertiesDesc: "\u9009\u62E9\u5217\u8868\u7C7B\u578B\u7684\u5C5E\u6027\u5E76\u6DFB\u52A0\u3002",
    showNoticeName: "\u4FEE\u6539\u5C5E\u6027\u65F6\u63D0\u793A",
    showNoticeDesc: "\u63D2\u4EF6\u81EA\u52A8\u4FEE\u6539\u5C5E\u6027\u65F6\uFF0C\u663E\u793A\u901A\u77E5\u63D0\u9192\u3002",
    addButton: "\u6DFB\u52A0",
    warning: "\u90E8\u5206\u76D1\u542C\u5C5E\u6027\u5728 Obsidian \u5C5E\u6027\u8BBE\u7F6E\u4E2D\u4E0D\u662F\u5217\u8868\u7C7B\u578B\uFF0C\u63D2\u4EF6\u65E0\u6CD5\u751F\u6548\u3002\u8BF7\u5148\u8F6C\u6362\u540E\u518D\u4F9D\u8D56\u81EA\u52A8\u6E05\u7406\u3002",
    uniquePropertiesGroup: "\u5355\u4E00\u503C\u5C5E\u6027\u5217\u8868",
    uniquePropertiesDesc: "\u4EE5\u4E0B\u5C5E\u6027\u53EA\u4F1A\u4FDD\u7559\u5355\u4E2A\u503C\uFF0C\u9002\u7528\u4E8E\u300C\u4F18\u5148\u7EA7\u300D\u8FD9\u7C7B\u201C\u5355\u9009\u201D\u7684\u60C5\u51B5\u3002",
    uniquePropertiesUpdateDesc: "\u6BCF\u6B21\u5C5E\u6027\u53D1\u751F\u53D8\u52A8\u7684\u65F6\u5019\uFF0C\u90FD\u4F1A\u81EA\u52A8\u66F4\u65B0\u5E76\u63D0\u793A\u3002",
    removeTooltip: "\u79FB\u9664",
    convertPropertyTypeButton: "\u8F6C\u6362\u5C5E\u6027\u7C7B\u578B",
    convertPropertyTypeTooltip: "\u5C06\u8BE5\u5C5E\u6027\u8F6C\u6362\u4E3A\u5217\u8868\u7C7B\u578B\u3002\u8FD9\u4E2A\u64CD\u4F5C\u53EA\u5F71\u54CD\u5C5E\u6027\uFF0C\u4E0D\u4F1A\u4FEE\u6539\u5DF2\u6709\u7B14\u8BB0\u3002",
    configuredAsList: "\u6B64\u5C5E\u6027\u5DF2\u914D\u7F6E\u4E3A\u5217\u8868\u7C7B\u578B\uFF0C\u6DFB\u52A0\u65B0\u503C\u65F6\u53EA\u4F1A\u4FDD\u7559\u6700\u65B0\u7684\u503C\uFF0C\u4EE5\u786E\u4FDD\u552F\u4E00\u3002",
    notRegistered: "\u6B64\u5C5E\u6027\u5C1A\u672A\u6CE8\u518C\u5230 Obsidian \u5C5E\u6027\u8BBE\u7F6E\u3002",
    notListType: "\u6B64\u5C5E\u6027\u5F53\u524D\u7C7B\u578B\u4E3A {type}\uFF0C\u4E0D\u662F\u5217\u8868\u7C7B\u578B\uFF0C\u63D2\u4EF6\u65E0\u6CD5\u751F\u6548\u3002"
  }
};
var zh_default = zh;

// src/i18n.ts
var LOCALES = {
  en: en_default,
  zh: zh_default,
  "zh-cn": zh_default,
  "zh-tw": zh_default
};
function getMessages() {
  var _a, _b;
  const language = (0, import_obsidian.getLanguage)().toLowerCase();
  return (_b = (_a = LOCALES[language]) != null ? _a : LOCALES[language.split("-")[0]]) != null ? _b : en_default;
}
function formatMessage(template, values) {
  return Object.entries(values).reduce(
    (message, [key, value]) => message.split(`{${key}}`).join(value),
    template
  );
}

// src/property-utils.ts
var import_obsidian2 = require("obsidian");
var LIST_PROPERTY_TYPES = /* @__PURE__ */ new Set(["aliases", "list", "multitext", "tags"]);
async function getPropertyTypeIssues(app, properties) {
  const types = getPropertyInfoMap(app);
  return properties.map((property) => {
    var _a, _b;
    return { property, type: (_b = (_a = getPropertyInfo(types, property)) == null ? void 0 : _a.widget) != null ? _b : null };
  }).filter((issue) => !issue.type || !LIST_PROPERTY_TYPES.has(issue.type));
}
function getPropertyTypeEntries(app) {
  const properties = getPropertyInfoMap(app);
  return Object.values(properties).map((info) => ({ property: info.name, type: info.widget })).sort((a, b) => a.property.localeCompare(b.property));
}
async function convertPropertyTypeToList(app, property, messages) {
  const metadataTypeManager = app.metadataTypeManager;
  await metadataTypeManager.setType(property, "multitext");
  new import_obsidian2.Notice(formatMessage(messages.notices.convertedPropertyType, { property }));
}
function getPropertyInfoMap(app) {
  const metadataCache = app.metadataCache;
  return metadataCache.getAllPropertyInfos();
}
function getPropertyInfo(properties, property) {
  var _a;
  return (_a = properties[property.toLowerCase()]) != null ? _a : null;
}

// src/settings-tab.ts
var SingleChoicePropertySettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.icon = "lucide-list-check";
    this.plugin = plugin;
  }
  display() {
    void this.render();
  }
  async render() {
    const { containerEl } = this;
    const messages = this.plugin.messages;
    containerEl.empty();
    let propertyInput;
    const propertyTypes = getPropertyTypeEntries(this.app);
    const addProperty = async () => {
      const property = propertyInput.getValue().trim();
      if (!property) {
        new import_obsidian3.Notice(messages.notices.enterPropertyName);
        return;
      }
      if (this.plugin.settings.properties.includes(property)) {
        new import_obsidian3.Notice(formatMessage(messages.notices.alreadyWatched, { property }));
        return;
      }
      this.plugin.settings.properties.push(property);
      await this.plugin.saveSettings();
      this.display();
    };
    new import_obsidian3.Setting(containerEl).setName(messages.settings.watchedPropertiesName).setDesc(messages.settings.watchedPropertiesDesc).addText(
      (text) => text.setPlaceholder("Status").then((component) => {
        propertyInput = component;
        new PropertySuggest(this.app, component.inputEl, propertyTypes).onSelect((value) => {
          component.setValue(value.property);
        });
        component.inputEl.addEventListener("keydown", (event) => {
          if (event.isComposing || event.key !== "Enter") {
            return;
          }
          event.preventDefault();
          void addProperty();
        });
      })
    ).addButton(
      (button) => button.setButtonText(messages.settings.addButton).setCta().onClick(() => {
        void addProperty();
      })
    );
    new import_obsidian3.Setting(containerEl).setName(messages.settings.showNoticeName).setDesc(messages.settings.showNoticeDesc).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showNotice).onChange(async (value) => {
        this.plugin.settings.showNotice = value;
        await this.plugin.saveSettings();
      })
    );
    const issues = await getPropertyTypeIssues(this.app, this.plugin.settings.properties);
    const group = new import_obsidian3.SettingGroup(containerEl).setHeading(messages.settings.uniquePropertiesGroup).addClass("single-choice-property-property-list");
    const groupDescEl = createGroupDescription(group.listEl);
    groupDescEl.setText(messages.settings.uniquePropertiesDesc);
    groupDescEl.createEl("br");
    groupDescEl.appendText(messages.settings.uniquePropertiesUpdateDesc);
    if (issues.length > 0) {
      groupDescEl.createEl("br");
      groupDescEl.createSpan({ cls: "single-choice-property-warning", text: messages.settings.warning });
    }
    for (const property of this.plugin.settings.properties) {
      const issue = issues.find((item) => item.property === property);
      group.addSetting((setting) => {
        setting.setName(property).setDesc(
          issue ? getIssueDescription(issue, messages) : messages.settings.configuredAsList
        );
        if (issue) {
          setting.addButton(
            (button) => button.setButtonText(messages.settings.convertPropertyTypeButton).setTooltip(messages.settings.convertPropertyTypeTooltip).onClick(async () => {
              await convertPropertyTypeToList(this.app, property, messages);
              this.display();
            })
          );
        }
        setting.addExtraButton(
          (button) => button.setIcon("trash").setTooltip(messages.settings.removeTooltip).onClick(async () => {
            this.plugin.settings.properties = this.plugin.settings.properties.filter(
              (item) => item !== property
            );
            await this.plugin.saveSettings();
            this.display();
          })
        );
      });
    }
  }
};
function createGroupDescription(containerEl) {
  const settingEl = containerEl.createDiv({
    cls: "setting-item settings-view__group-description",
    attr: { tabindex: "-1" }
  });
  const infoEl = settingEl.createDiv({ cls: "setting-item-info" });
  infoEl.createDiv({ cls: "setting-item-name" });
  return infoEl.createDiv({ cls: "setting-item-description" });
}
var PropertySuggest = class extends import_obsidian3.AbstractInputSuggest {
  constructor(app, inputEl, propertyTypes) {
    super(app, inputEl);
    this.propertyTypes = propertyTypes;
  }
  getSuggestions(query) {
    const normalizedQuery = query.trim().toLowerCase();
    const suggestions = normalizedQuery ? this.propertyTypes.filter(
      (entry) => entry.property.toLowerCase().includes(normalizedQuery)
    ) : this.propertyTypes;
    return suggestions.slice(0, 50);
  }
  renderSuggestion(value, el) {
    el.addClass("single-choice-property-suggestion");
    el.createSpan({ cls: "single-choice-property-suggestion-name", text: value.property });
    el.createSpan({ cls: "single-choice-property-suggestion-type", text: value.type });
  }
  selectSuggestion(value) {
    this.setValue(value.property);
    this.close();
  }
};
function getIssueDescription(issue, messages) {
  if (!issue.type) {
    return messages.settings.notRegistered;
  }
  return formatMessage(messages.settings.notListType, { type: issue.type });
}

// src/types.ts
var DEFAULT_SETTINGS = {
  properties: ["status"],
  showNotice: true
};

// src/enforcer.ts
var import_obsidian4 = require("obsidian");
function enforceFrontmatterObject(frontmatter, properties) {
  const changes = [];
  for (const property of properties) {
    const value = frontmatter[property];
    if (!Array.isArray(value) || value.length <= 1) {
      continue;
    }
    const keptValue = value[value.length - 1];
    frontmatter[property] = [keptValue];
    changes.push({ property, keptValue });
  }
  return changes;
}
function showEnforceNotice(file, changes, messages) {
  if (changes.length === 0) {
    return;
  }
  for (const change of changes) {
    new import_obsidian4.Notice(
      formatMessage(messages.notices.keptLatestValue, {
        property: change.property,
        file: file.basename,
        value: String(change.keptValue)
      })
    );
  }
}
async function enforceSingleChoiceProperty(app, file, properties, messages, showNotice) {
  let changes = [];
  let updatedFrontmatter = null;
  await app.fileManager.processFrontMatter(file, (frontmatter) => {
    changes = enforceFrontmatterObject(frontmatter, properties);
    updatedFrontmatter = { ...frontmatter };
  });
  if (showNotice) {
    showEnforceNotice(file, changes, messages);
  }
  return {
    changed: changes.length > 0,
    frontmatter: updatedFrontmatter
  };
}

// main.ts
var SingleChoicePropertyPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.processingPaths = /* @__PURE__ */ new Set();
  }
  async onload() {
    await this.loadSettings();
    this.messages = getMessages();
    this.addSettingTab(new SingleChoicePropertySettingTab(this.app, this));
    this.registerEvent(
      this.app.metadataCache.on("changed", (file) => {
        void this.enforceFile(file.path);
      })
    );
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    this.settings.properties = normalizeProperties(this.settings.properties);
  }
  async saveSettings() {
    this.settings.properties = normalizeProperties(this.settings.properties);
    await this.saveData(this.settings);
  }
  async enforceFile(path) {
    if (this.processingPaths.has(path)) {
      return;
    }
    const file = this.app.vault.getFileByPath(path);
    if (!file || file.extension !== "md") {
      return;
    }
    this.processingPaths.add(path);
    try {
      const result = await enforceSingleChoiceProperty(
        this.app,
        file,
        this.settings.properties,
        this.messages,
        this.settings.showNotice
      );
      if (result.changed) {
        this.refreshOpenFileViews(file, result.frontmatter);
      }
    } finally {
      this.processingPaths.delete(path);
    }
  }
  refreshOpenFileViews(file, frontmatter) {
    this.app.workspace.getLeavesOfType("markdown").forEach((leaf) => {
      var _a;
      const view = leaf.view;
      if (!(view instanceof import_obsidian5.MarkdownView) || ((_a = view.file) == null ? void 0 : _a.path) !== file.path) {
        return;
      }
      synchronizeMetadataEditor(view, frontmatter);
      forceRenderMetadataRows(view, frontmatter, this.settings.properties);
    });
  }
};
function synchronizeMetadataEditor(view, frontmatter) {
  const owner = view;
  if (owner.metadataEditor) {
    owner.metadataEditor.synchronize(frontmatter);
  }
}
function forceRenderMetadataRows(view, frontmatter, properties) {
  if (!frontmatter) {
    return;
  }
  const owner = view;
  const metadataEditor = owner.metadataEditor;
  if (!metadataEditor) {
    return;
  }
  for (const property of properties) {
    const row = metadataEditor.rendered.find((item) => item.entry.key === property);
    if (!row || !(property in frontmatter)) {
      continue;
    }
    row.renderProperty({ key: property, value: frontmatter[property] }, true);
  }
}
function normalizeProperties(properties) {
  const seen = /* @__PURE__ */ new Set();
  const normalized = [];
  for (const property of properties) {
    const trimmed = property.trim();
    if (trimmed && !seen.has(trimmed)) {
      seen.add(trimmed);
      normalized.push(trimmed);
    }
  }
  return normalized.length > 0 ? normalized : [...DEFAULT_SETTINGS.properties];
}
